version: '3'
services:
  code-challenge:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      MONGO_URL: mongodb://mongodb:27017/db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DEFAULT_EXPIRE_CACHE: 300
    depends_on:
      - mongodb
      - redis
    links:
      - mongodb
      - redis

  mongodb:
    image: mongo:4
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"

  portainer:
    image: portainer/portainer
    ports:
      - '9000:9000'
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  mongo_data: {}
  portainer_data: {}
